spring:
  profiles:
    active:
      - db
application:
  name: 331-lab09-3
datasource:
  url: jdbc:mysql://localhost:3308/lab09-3db?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
